# SonarCloud Configuration file
# Define files/directories to exclude from source code analysis
sonar.exclusions=coverage/**,dist/**,dist-ssr/**,build/**,storybook-static/**,node_modules/**,public/**,.git/**,.github/**,.husky/**

# Specify where the code coverage report is located so it can read it natively (optional)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
